import ESG from "../../Images/ESG.png";
import WealthManagement from "../../Images/WealthManagement.png";
import InvestmentManagement from "../../Images/InvestmentManagement.png";

export const InitialStateLandingCard = {
  ContentHeading: "Hello Vipul",
  ContentSubHeading: "How can i help you today?",
  images: [
    {
      src: ESG,
      label: "ESG",
      style: { width: "230px", height: "289.8px", flexShrink: 0 },
      description:" Widespread group of squamate reptiles, with over species, ranging across all continents except Antarctica"
    },
    {
      src: WealthManagement,
      label: "WealthManagement",
      style: { width: "250px", height: "315px", flexShrink: 0 },
      description:" Widespread group of squamate reptiles, with over species, ranging across all continents except Antarctica"
    },
    {
      src: InvestmentManagement,
      label: "InvestmentManagement",
      style: { width: "230px", height: "289.8px", flexShrink: 0 },
      description:" Widespread group of squamate reptiles, with over species, ranging across all continents except Antarctica"
    },
  ],
  CardActionArea: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    background: "transparent",
  },
  CardContent: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
  },
  DarkTheme: {
    ContentHeading: {
      color: "rgba(250, 250, 250, 0.95)",
      leadingTrim: "both",
      display: "flex",
      textEdge: "cap",
      fontFamily: "Poppins Next",
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: "500",
      lineHeight: "0px",
    },
    ContentHeadingName: {
      color: "#3F9CFF",
      leadingTrim: "both",
      textEdge: "cap",
      fontFamily: "Poppins Next",
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: "500",
      lineHeight: "0px",
    },
    ContentSubHeading: {
      leadingTrim: "both",
      textEdge: "cap",
      fontFamily: "Poppins Next",
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: "500",
      lineHeight: "0px",
      color: "grey",
      backgroundClip: "text",
    },
    CardLabel: {
      color: "#3F9CFF",
      textAlign: "center",
      leadingTrim: "both",
      textEdge: "cap",
      fontFamily: "Poppins",
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: "800",
      lineHeight: "20px",
      letterSpacing: "-0.36px",
    },
    CardDescription: {
      color: "#DEDEDE",
      textAlign: "center",
      fontFamily: "Poppins",
      fontSize: "13px",
      fontStyle: "normal",
      fontWeight: "400",
      lineHeight: "180%",
    },
  },
  LightTheme: {
    ContentHeading: {
      color: "black",
      display: "flex",
      leadingTrim: "both",
      textEdge: "cap",
      fontFamily: "Poppins Next",
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: "500",
      lineHeight: "0px",
    },
    ContentHeadingName: {
      color: "#968864",
      leadingTrim: "both",
      textEdge: "cap",
      fontFamily: "Poppins Next",
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: "500",
      lineHeight: "0px",
    },
    ContentSubHeading: {
      leadingTrim: "both",
      textEdge: "cap",
      fontFamily: "Poppins Next",
      fontSize: "48px",
      fontStyle: "normal",
      fontWeight: "500",
      lineHeight: "0px",
      background: "#424241",
      backgroundClip: "text",
    },
    CardLabel: {
      color: "#968864",
      textAlign: "center",
      leadingTrim: "both",
      textEdge: "cap",
      fontFamily: "Poppins",
      fontSize: "18px",
      fontStyle: "normal",
      fontWeight: "800",
      lineHeight: "20px",
      letterSpacing: "-0.36px",
    },
    CardDescription: {
      color: "var(--Light-Body-Text, #2C2C2C)",
      textAlign: "center",
      fontFamily: "Poppins",
      fontSize: "13px",
      fontStyle: "normal",
      fontWeight: "400",
      lineHeight: "180%",
    },
  },
};
